// Kconfig → Rust 的窄运输契约（解析 / 校验的纯函数），与 host test 共用同一份
// 实现：build script 侧以 `#[path]` 引入，arch lib 侧只在 `cfg(test)` 编译。
//
// 与 `os/core/build.rs` 的 `TRACE_CAPACITY` 同一条契约。为什么这个常量在
// `arch`：`core` 依赖 `arch`，`arch` 不能依赖 `core`，而两边都要用同一个容量；
// 常量必须落在叶子 `arch`，由 `core` re-export（见 os/core/Kconfig 的 MAX_CPUS）。
#[path = "src/build_config.rs"]
mod build_config;

use build_config::parse_max_cpus;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-env-changed=CONFIG_MAX_CPUS");
    let raw = std::env::var("CONFIG_MAX_CPUS").ok();
    let bare_metal = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("none");
    let value = match parse_max_cpus(raw.as_deref(), bare_metal) {
        Ok(value) => value,
        Err(error) => panic!(
            "CONFIG_MAX_CPUS={raw:?} is not a valid resolved Kconfig value: \
             {error:?} (bare-metal builds get it from `make kernel`; see docs/architecture/kconfig.md)"
        ),
    };
    let out = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    fs::write(
        out.join("max_cpus.rs"),
        format!(
            "// Generated by arch/build.rs from the CONFIG_MAX_CPUS env var \
             (Kconfig MAX_CPUS).\n\
             /// 编译期 per-CPU 容量（Kconfig `MAX_CPUS` 的 resolved 值）。\n\
             pub const MAX_CPUS: usize = {value};\n"
        ),
    )
    .unwrap();
}
