//! `filesystem` service contract shared by VFS and filesystem providers.
//!
//! The declaration bodies (`FileSystemApi` + name / fingerprint / open-read flag)
//! are generated by `tools/kabi/kabi_gen.py` from `abi/filesystem.toml`
//! ([`crate::generated::filesystem`]); this module keeps the semantic facade and
//! re-exports the existing paths.
//!
//! The first contract is deliberately small and read-only.  A provider keeps
//! its implementation objects private; callers receive only an opaque u64
//! file handle.

use crate::binding::{InterfaceAbi, InterfaceKind, Service};

/// Stable endpoint name for the singleton filesystem service.
pub use crate::generated::filesystem::KCOMP_FILESYSTEM_NAME as FILESYSTEM_NAME;

use crate::generated::filesystem::KCOMP_FILESYSTEM_ABI;

/// Exact ABI fingerprint for `FileSystemApi`.
///
/// raw `u64` 本体在生成物（[`KCOMP_FILESYSTEM_ABI`]，schema 单一来源）；
/// [`InterfaceAbi`] newtype 由手写 `binding.rs` 定义，这里做包装。
pub const FILESYSTEM_ABI: InterfaceAbi = InterfaceAbi::from_raw(KCOMP_FILESYSTEM_ABI);

/// Read-only open flag.  This is a KaleidOS ABI value, not a FatFs `FA_*` value.
pub use crate::generated::filesystem::KCOMP_FILESYSTEM_OPEN_READ as FILESYSTEM_OPEN_READ;

/// `filesystem` provider/consumer function table.
///
/// 定义与布局断言在生成物 [`crate::generated::filesystem`]
/// （schema = `abi/filesystem.toml`）；这里 re-export 保持既有路径。
pub use crate::generated::filesystem::FileSystemApi;

/// The generic filesystem contract.  Concrete providers include FatFs, Ext4,
/// and Tmpfs; the VFS binds this contract without knowing the format.
pub struct FileSystem;

impl Service for FileSystem {
    const NAME: &'static [u8] = FILESYSTEM_NAME;
    const KIND: InterfaceKind = InterfaceKind::Service;
    const ABI: InterfaceAbi = FILESYSTEM_ABI;
    type Api = FileSystemApi;
}
