// Transport resolved build values; test artifacts are prepared by make test-host.
#[path = "src/build_config.rs"]
mod build_config;
use build_config::parse_trace_capacity;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let out = PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
    transport_trace_capacity(&out);
    println!("cargo:rerun-if-env-changed=KALEIDOS_GIT_COMMIT");
    if let Ok(commit) = std::env::var("KALEIDOS_GIT_COMMIT") {
        println!("cargo:rustc-env=KALEIDOS_GIT_COMMIT={commit}");
    }
}

/// Kconfig `TRACE_CAPACITY` → Rust 常量的运输：Makefile 把生成的片段里的
/// `CONFIG_TRACE_CAPACITY` 作为环境变量传入，这里校验后写 OUT_DIR 文件，由
/// `trace::ring` 的 `include!` 消费。**不读 `.config`**；裸机构建缺值 / 越界
/// 直接报错（不发明默认），host 构建用显式默认。
fn transport_trace_capacity(out: &Path) {
    println!("cargo:rerun-if-env-changed=CONFIG_TRACE_CAPACITY");
    let raw = std::env::var("CONFIG_TRACE_CAPACITY").ok();
    let bare_metal = std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("none");
    let capacity = match parse_trace_capacity(raw.as_deref(), bare_metal) {
        Ok(capacity) => capacity,
        Err(error) => panic!(
            "CONFIG_TRACE_CAPACITY={raw:?} is not a valid resolved Kconfig value: \
             {error:?} (bare-metal builds get it from `make kernel`; see docs/architecture/kconfig.md)"
        ),
    };
    fs::write(
        out.join("trace_capacity.rs"),
        format!(
            "// Generated by build.rs from the CONFIG_TRACE_CAPACITY env var \
             (Kconfig TRACE_CAPACITY).\n\
             /// 目标端 ring 容量（records）——Kconfig `TRACE_CAPACITY` 的 resolved 值。\n\
             pub const TRACE_CAPACITY: usize = {capacity};\n"
        ),
    )
    .unwrap();
}
