[package]
name = "kernel"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
arch = { path = "../arch" }
buddy_system_allocator = { path = "../../third_party/buddy_system_allocator", default-features = false, features = ["alloc", "use_spin", "metadata_heap"] }
spin = { version = "0.12.1", default-features = false, features = ["spin_mutex", "rwlock","once"] }
